FROM alpine

WORKDIR /app

RUN apk add --no-cache git nodejs nodejs-npm && \
    git clone https://github.com/docker-hy/frontend-example-docker.git . && \
    npm install && \
    npm install -g serve && \
    npm run build && \
    apk del git nodejs-npm && \
    ls | grep -v dist | xargs rm -rf && \
    adduser -D app && \
    chown -R app /app

USER app

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "dist"]
