FROM ubuntu:16.04

WORKDIR /home/node/app

RUN apt-get update && apt-get install -y git curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    git clone https://github.com/docker-hy/backend-example-docker.git . && \
    apt-get install -y nodejs && \
    npm i && \
    useradd app && chown -R app /home/node/app

EXPOSE 8000

CMD ["npm", "start"]
