jobs:
  setup:
    steps:
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
  build:
    executor: docker/docker
    steps:
        - setup_remote_docker
        - checkout
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
        - docker/push:
            digest-path: /tmp/digest.txt
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
        - run: docker tag docker.io/$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:${tag}} registry.heroku.com/${HEROKU_APP_NAME}/web
        - run: docker push registry.heroku.com/${HEROKU_APP_NAME}/web

  deploy:
    parameters:
      app-name:
        description: "The Heroku app name to which the application should be deployed"
        type: string
      app-arg:
        description: "The Heroku Dockerfile args"
        type: string
      app-type:
        description: "The Heroku app type (web or worker) of the application to be deployed"
        type: string
        default: "web"
    steps:
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push << parameters.app-type >> -a << parameters.app-name >> --arg << parameters.app-arg >>
            heroku container:release << parameters.app-type >> -a << parameters.app-name >>
orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter




